/**
 * vectortable definition
 * 
 * This File defines a standard Vectortable for M5213 Coldfire Processor.
 * ISRs are defined in isr.c / .h
 * 
 * locator puts vtbl[] in a seperate section S_vtbl locatet @ 0x0000   
**/
#include "isr.h"
#pragma seperate vtbl
long vtbl[254] = {
(long) 0x00008000,
(long) 0x00000800,
(long) &AccessErrorIsr,  //vector 2
(long) &AddressErrorIsr, 
(long) &IllegalInstructionIsr,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &PrivilegeViolationIsr,
(long) &TraceIsr,
(long) &UnimpOpcodeAIsr,  //vector 10
(long) &UnimpOpcodeFIsr,
(long) &DebugIsr,  
(long) &UnhandledInterrupt,
(long) &FormatErrorIsr,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  //vector 20
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  //vector 30
(long) &UnhandledInterrupt,
(long) &TrapIsr,  
(long) &TrapIsr,
(long) &TrapIsr,
(long) &TrapIsr,
(long) &TrapIsr,
(long) &TrapIsr,
(long) &TrapIsr,
(long) &TrapIsr,
(long) &TrapIsr,  //vector 40
(long) &TrapIsr,
(long) &TrapIsr,  
(long) &TrapIsr,
(long) &TrapIsr,
(long) &TrapIsr,
(long) &TrapIsr,
(long) &TrapIsr,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  //vector 50
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  //vector 60
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &EdgePortFlag1Isr,  //MCF5213 interrupt sources begin here
(long) &EdgePortFlag2Isr,
(long) &EdgePortFlag3Isr,
(long) &EdgePortFlag4Isr,
(long) &EdgePortFlag5Isr,
(long) &EdgePortFlag6Isr,  //vector 70
(long) &EdgePortFlag7Isr,
(long) &SoftwareWatchdogTimeoutIsr,  
(long) &DMA0TransferCompleteIsr,
(long) &DMA1TransferCompleteIsr,
(long) &DMA2TransferCompleteIsr,
(long) &DMA3TransferCompleteIsr,
(long) &UART0Isr,
(long) &UART1Isr,
(long) &UART2Isr,
(long) &UnhandledInterrupt,  //vector 80
(long) &I2Cisr,  
(long) &QSPIisr,
(long) &TMR0Isr,  
(long) &TMR1Isr,
(long) &TMR2Isr,
(long) &TMR3Isr,
(long) &MessageBuffer0Isr,
(long) &MessageBuffer1Isr,
(long) &MessageBuffer2Isr,
(long) &MessageBuffer3Isr,  //vector 90
(long) &MessageBuffer4Isr,  
(long) &MessageBuffer5Isr,
(long) &MessageBuffer6Isr,
(long) &MessageBuffer7Isr,
(long) &MessageBuffer8Isr,
(long) &MessageBuffer9Isr,
(long) &MessageBuffer10Isr,
(long) &MessageBuffer11Isr,
(long) &MessageBuffer12Isr,
(long) &MessageBuffer13Isr,  //vector 100
(long) &MessageBuffer14Isr,  
(long) &MessageBuffer15Isr,
(long) &ErrorInterruptIsr,  
(long) &BusOffInterruptIsr,
(long) &TimerOverflowIsr,
(long) &PulseAccumulatorInputIsr,
(long) &PulseAccumulatorOverflowIsr,
(long) &Timer0Isr,
(long) &Timer1Isr,
(long) &Timer2Isr,  //vector 110
(long) &Timer3Isr,  
(long) &LVDIsr,
(long) &ADCAconversionCompleteIsr,  
(long) &ADCBconversionCompleteIsr,
(long) &ADCisr,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 110
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &SGFMbufferEmptyIsr,
(long) &SGFMcommandCompleteIsr,
(long) &ProtectionViolationIsr,
(long) &AccessError5213Isr,
(long) &PWMInterruptIsr,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 130
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 140
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 150
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 160
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 170
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 180
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 190
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 200
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 210
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 220
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 230
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 240
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt,  //vector 250
(long) &UnhandledInterrupt,
(long) &UnhandledInterrupt,  
(long) &UnhandledInterrupt
};